version: '3.8'
services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: always
    volumes:
      - '/:/host:ro,rslave'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "0:0"
    ports:
      - '9090:9090'
    restart: always
    environment:
      - TZ=America/Detroit
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    labels:
      - homepage.group=Containers
      - homepage.name=Prometheus
      - homepage.icon=prometheus.png
      - homepage.href=http://10.100.10.20:9090/
    
  pve-exporter:
    image: prompve/prometheus-pve-exporter
    container_name: pve-exporter
    ports:
      - '9221:9221'
    restart: unless-stopped
    volumes:
      - ./pve.yml:/etc/prometheus/pve.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "0:0"
    ports:
      - '3000:3000'
    environment:
      - TZ=America/Detroit
    restart: unless-stopped
    volumes:
      - ./grafana_data:/var/lib/grafana
    labels:
      - homepage.group=Containers
      - homepage.name=Grafana
      - homepage.icon=grafana.png
      - homepage.href=http://10.100.10.20:3000/
