site_name: Spicy Docs
site_url: https://spicyfajitas.github.io/cookbooks/
repo_url: https://github.com/spicyFajitas/cookbooks/

docs_dir: "cookbooks/"

#plugins
plugins:
  - search
  # - mermaid2

extra_css:
  - css/extra.css

# enable features
features:
  - content.code.copy
  - navigation.indexes
  - navigation.instant
  - navigation.path
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.tracking
  - toc.follow
  - toc.integrate 

# page tree
# nav:
#   - Home: index.md
#   - Documentation: 
#     - Proxmox: documentation/Proxmox.md
#     - Router: documentation/Router.md
#     - Hardware Inventory: documentation/Hardware Inventory.md
#     - Networking: documentation/Networking.md
#     - Subnetting: documentation/Subnetting Plans.md
#     - Linux: documentation/Linux.md
#     - Netbox: documentation/Netbox.md
#   - Projects:
#     - Projects: projects/Projects.md
#   - Work Experience: 
#     - Work Experience: work experience/Work Experience.md
#   - Classes:
#     - Linux Admin: classes/sat2711/info.md
#   - Reference: Reference.md

# colors
theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_javascript:
  - 'javascript/mermaid.min.js'

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - def_list
  - md_in_html
  - meta
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
