all:
  hosts:
  children:
    netbox:
      hosts:
        10.100.10.26:
    k3s:
      hosts:
        192.168.1.43:
        192.168.1.233:
        192.168.1.76:
    test-k3s:
      hosts:
        192.168.1.144:
    cloud kuma:
      hosts:
        68.183.137.200:
