---
version: "3.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1002
      - PGID=13000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /opt/media/sonar:/config
      - /opt/media/media-files:/data
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1002
      - PGID=13000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /opt/media/radarr:/config
      - /opt/media/media-files:/data
    ports:
      - "7878:7878"
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Chicago
    ports:
      - 5055:5055
    volumes:
      - /opt/media/jellyseer:/app/config
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1001
      - PGID=13000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /opt/media/prowlarr:/config
    network_mode: "service:gluetun"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1002
      - PGID=13000
      - UMASK=002
      - TZ=America/Chicago
      - WEBUI_PORT=8080
    volumes:
      - /opt/media/qbittorrent:/config
      - /opt/media/media-files:/data/torrents
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - gluetun:/gluetun
    ports:
      - "9696:9696"
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=<redacted>
      - OPENVPN_PASSWORD=<redacted>
      - SERVER_REGIONS=Netherlands