---
# tasks file for installing netbox
- name: Update apt-get repo and cache
    apt: 
    update_cache: yes
    upgrade: yes
    register: apt_output
- name: Upgrade all apt packages
  apt: upgrade=dist

- name: install required packages
  package: 
    name: postgresql
    state: installed

- name: Start service httpd, if not started
  ansible.builtin.service:
    name: postgresql
    enabled: true
    state: started

- 