---
- name: Run speedtest-tracker playbook
  hosts: speedtest_tracker
  become: true
  become_method: sudo
  roles:
    - speedtest-tracker
  vars_files:
    - roles/speedtest-tracker/vaults/production.yml
