- name: Install uptime kuma in the cloud
  hosts: cloud_kuma
  become: true
  become_method: sudo
  roles:
    - uptime_kuma
  vars_files:
    - roles/uptime_kuma/vaults/production.yml
  tasks:
    - name: include task file for cloud instance
      include: roles/uptime_kuma/tasks/cloud_kuma.yml

- name: Install uptime kuma on prem
  hosts: local_kuma
  become: true
  become_method: sudo
  roles:
    - uptime_kuma
  vars_files:
    - roles/uptime_kuma/vaults/production.yml
  tasks:
    - name: include task file for on prem instance
      include: roles/uptime_kuma/tasks/local_kuma.yml

## to do
## mkdir task for /opt kuma

## create new role [baseline] to ensure baseline packages are
## installed on servers bc not having them is fucking annoying