---
- name: Update Ubuntu Servers
  hosts: k3s
  become: true
  become_user: adam
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      register: update_cache

    - name: Upgrade packages
      apt:
        upgrade: dist
        update_cache: yes
      when: update_cache.changed