---
- name: Update Ubuntu Servers
  hosts: k3s
  become: yes
  become_user: adam
  tasks:
    - name: Update cache 
      apt:
        update_cache: yes

    - name: Upgrade all packages on servers
      apt: 
        name: "*"
        state: latest