# ~/docker_compose/netbox/docker-compose.yml
# netbox container

version: '3.4'

services:
  netbox:
    image: linuxserver/netbox:latest
    container_name: netbox
    restart: always
    ports: 
    - "8000:8000"
    - "8001:8001"

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: