# ~/docker_compose/netbox/docker-compose.yml
# netbox container

version: '3'
services:
  netbox:
    image: netboxcommunity/netbox:latest
    ports:
      - "8000:8080"
    volumes:
      - ./netbox:/opt/netbox/netbox/media
    environment:
      - SECRET_KEY=
      - ALLOWED_HOSTS=
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=netbox
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=netbox
      - HOST

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: